const Sintar = () => {
    return (
        <div className="sintar">
            <h1 className="sintar_header">Fundacja Sintar im. Issy Adajewa</h1>
            <div className="sintar_div">
                <p className="sintar_text">
                    W 2003 roku, idąc za pomysłem Issy  Adajewa, byłego dyrektora czeczeńskiego  Muzeum Narodowego i wybitnego  znawcy czeczeńskiej kultury, powstało  stowarzyszenie Instytut Kultury Narodów Kaukazu, którego celem jest  upowszechnianie wiedzy o Kaukazie,  wiążących Polskę z tym regionem tradycjach,  wspólnych wartościach i inspiracjach oraz  ratowanie ginącej, unikatowej czeczeńskiej  kultury – pod wieloma względami bardzo  przypominającej kulturę staropolską i system  polityczny zbudowany w Rzeczypospolitej.  Cele stowarzyszenia realizowaliśmy przez  działalność popularyzatorską, w tym liczne  wystawy, prelekcje, wykłady, spotkania,  prezentacje kultury oraz publikacje w języku  polskim (wydaliśmy fundamentalną  pracę Issy Adajewa o dziejach i kulturze  Czeczenów „Kamienie mówią” i tomik  poezji czeczeńskiej, a w przygotowaniu  pozostała „Mała antologia literatury  czeczeńskiej”, niedokończona przez Autora,  zmarłego w 2012 roku, wymagająca jeszcze  uzupełnień i tłumaczeń). <br/><br/>
                    Jednocześnie staraliśmy się wspierać  emigrantów czeczeńskich w ich potrzebach kulturalnych i edukacyjnych,  na które brakuje miejsca w życiu emigranta  wojennego zaczynającego w Polsce od zera.  W 2009 roku założyliśmy w Warszawie,  korzystając z programów unijnych, Ośrodek  Samopomocy Uchodźców SINTAR,  przede wszystkim z myślą o zapobieżeniu  marginalizacji i o wyrównaniu szans  młodego pokolenia, aby w ten sposób  pomóc w odrodzeniu czeczeńskiej elity  intelektualnej, wymordowanej w rodzinnym  kraju. Ośrodek SINTAR (słowo sintar w języku czeczeńskim oznacza „wzrastanie,  rozkwitanie”) w ciągu tych lat wychował  już grupę utalentowanej i ambitnej  młodzieży, utożsamiającej się z Polską
                    jako drugą ojczyzną, aktywnej w życiu  szkolnym i publicznym, a zarazem dbającej  o zachowanie tradycji czeczeńskich  i troszczącej się o obraz swojej społeczności  w oczach Polaków. W 2015 roku utworzyliśmy Fundację Sintar im. Issy  Adajewa, która przy współpracy z Instytutem  Kultury Narodów Kaukazu przejęła opiekę  nad Ośrodkiem SINTAR. <br/><br/>
                    Ośrodek SINTAR był wyjątkową placówką  w skali europejskiej. Spośród innych  inicjatyw wspierających uchodźców  wyróżniały go: idea wykorzystania  doświadczeń polskiego uchodźstwa  w sposób odpowiadający współczesnym  warunkom; komplementarność i spójność  działań skierowanych do określonej,  największej grupy uchodźczej i zarazem do  polskiej społeczności; wreszcie – myślenie  w wieloletniej perspektywie. Przekładając to  na język praktyki sintarowej: nie interesowała  nas asymilacja w znaczeniu „przerobienia”  emigrantów na Polaków w jednym  pokoleniu i odebrania im tożsamości, bo  wychowalibyśmy ludzi wyobcowanych  z obu kręgów kulturowych; chcieliśmy dać  im równe szanse z polskimi rówieśnikami,  by mimo biedy w rodzinach i nierównego  startu w nauce nie znaleźli się w grupie  wykluczonych i zmarginalizowanych  społecznie; chcieliśmy, by przechowali to,  co najcenniejsze, a ginące w ich ojczyźnie;  chcieliśmy, by stali się obywatelami Polski,  nie przeżywając tak dobrze znanych  dzieciom emigranckim rozterek i wyborów  towarzyszących podwójnej tożsamości,  która powinna się stać ich bogactwem  i inspiracją. Ważną rolę pełnili w SINTARZE  rodzice – ich codzienna współpraca,  zrozumienie i akceptacja postawionych przez  nas celów wychowawczych, edukacyjnych  i integracyjnych, włączanie się w działania  odpowiednio do możliwości czasowych
                    i kompetencyjnych. Dzięki temu idea  i działania SINTARU obejmowały całe  rodziny i przyciągały coraz szersze grono  uchodźców. <br/><br/>
                    Ośrodek był współzarządzany przez  uchodźców, którzy pragną zarówno czerpać  z polskiej kultury, jak i prezentować własne  tradycje. Zorganizował wiele wystaw,  prezentacji, całodniowe imprezy otwarte  takie jak cykl „Dni czeczeńskich” dla  mieszkańców Warszawy; podjął współpracę  ze szkołami, instytucjami i organizacjami  zainteresowanymi problematyką
                    uchodźstwa. <br/><br/>
                    Jednak podstawową działalnością SINTARU  były pozaszkolne zajęcia dla czeczeńskich  dzieci i młodzieży, przygotowujące młode  pokolenie uchodźców do życia w Polsce  i szacunku do nowej Ojczyzny, a zarazem  wpływające na całe ich środowisko.  Corocznie z zajęć organizowanych  przez SINTAR korzystało od 60 do 80  młodych beneficjentów oraz dorośli  członkowie ich rodzin – i stale zgłaszali  się kolejni. W niektórych zajęciach  uczestniczyli także inni cudzoziemcy  z obszaru b. ZSRS, pragnący uczyć  się języka polskiego lub umożliwić  dzieciom korzystanie z pożytecznych,  nieodpłatnych zajęć po szkole. Zajęcia  te to warsztaty językowe (jęz. polski,  angielski i czeczeński), informatyczne,  plastyczne, taneczne, muzyczne, filmowe,  teatralne, a także praktyczne, jak
                    krawiectwo i majsterkowanie. Najmłodsze  dzieci przygotowywaliśmy do podjęcia  nauki w szkole, starsze wspomagaliśmy  w wyrównaniu szans edukacyjnych,  udzielając korepetycji. Dorośli mieli  możliwość korzystać w SINTARZE z lekcji  jęz. polskiego i zajęć informatycznych,  porad prawnych, doradztwa zawodowego  i kursów zawodowych.
                    SINTAR zachęcał dzieci i młodzież do  angażowania się w inicjatywy kulturalne  i charytatywne różnych instytucji i organizacji pozarządowych. <br/><br/>
                    Ośrodek okazał się trafnym przedsięwzięciem i dość szybko zaczął  przynosić oczekiwane efekty. Dzieci,  które w większości przychodziły do nas  wycofane, zniechęcone do szkoły, rozwinęły  się, ośmieliły, nabrały pewności siebie  i zaczęły odnosić sukcesy w nauce, udzielać  się w różnych konkursach szkolnych  i pozaszkolnych. SINTAR stał się miejscem,  które dzieci traktowały jak dom rodzinny. <br/><br/>
                    Na przełomie lat 2016/2017 (przez  4 miesiące) prowadziliśmy działania  wspierające dzieci uchodźców oczekujących  na decyzje azylowe w ośrodku dla  cudzoziemców w Lininie. Stanowiło to  poszerzenie naszej dotychczasowej praktyki  o inne, często dramatyczne problemy,  będące udziałem tej grupy – zdrowotne,  psychiczne, socjalne, szkolne – wynikające  z długotrwałego przebywania w odcięciu od  normalnego życia i niepewności dalszych  losów. <br/><br/>
                    Choć Fundacja nadal była aktywna  w przestrzeni publicznej (w ramach  konferencji, szkoleń, itp.), byliśmy  zmuszeni zawiesić działanie SINTARU  jako Ośrodka, ze względu na brak źródeł  finansowania naszej działalności.
                    Dziś, dwa lata po zawieszeniu, chcielibyśmy  go reaktywować. Szukamy prywatnych  sponsorów oraz instytucji, które pomogą  nam przywrócić do życia organizację,  która jest łącznikiem międzykulturowym,  placówką edukacyjną i wsparciem dla tak  wielu osób.<br/><br/>
                    nr konta: <br/> 92 2130 0004 2001 0723 8934 0001
                </p>
            </div>
        </div>
    )
}

export default Sintar;
